/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVocabRouteImport } from './routes/_authenticated.vocab'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated.tutor'
import { Route as AuthenticatedSprechenRouteImport } from './routes/_authenticated.sprechen'
import { Route as AuthenticatedSimuladosRouteImport } from './routes/_authenticated.simulados'
import { Route as AuthenticatedSchreibenRouteImport } from './routes/_authenticated.schreiben'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedLesenRouteImport } from './routes/_authenticated.lesen'
import { Route as AuthenticatedHoerenRouteImport } from './routes/_authenticated.hoeren'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated.flashcards'
import { Route as AuthenticatedErrosRouteImport } from './routes/_authenticated.erros'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedLearnLevelRouteImport } from './routes/_authenticated.learn.$level'
import { Route as AuthenticatedAdminIngestRouteImport } from './routes/_authenticated.admin.ingest'
import { Route as AuthenticatedLearnChapterSlugRouteImport } from './routes/_authenticated.learn.chapter.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVocabRoute = AuthenticatedVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSprechenRoute = AuthenticatedSprechenRouteImport.update({
  id: '/sprechen',
  path: '/sprechen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimuladosRoute = AuthenticatedSimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchreibenRoute = AuthenticatedSchreibenRouteImport.update({
  id: '/schreiben',
  path: '/schreiben',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLesenRoute = AuthenticatedLesenRouteImport.update({
  id: '/lesen',
  path: '/lesen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHoerenRoute = AuthenticatedHoerenRouteImport.update({
  id: '/hoeren',
  path: '/hoeren',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedErrosRoute = AuthenticatedErrosRouteImport.update({
  id: '/erros',
  path: '/erros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnLevelRoute = AuthenticatedLearnLevelRouteImport.update({
  id: '/learn/$level',
  path: '/learn/$level',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIngestRoute =
  AuthenticatedAdminIngestRouteImport.update({
    id: '/admin/ingest',
    path: '/admin/ingest',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnChapterSlugRoute =
  AuthenticatedLearnChapterSlugRouteImport.update({
    id: '/learn/chapter/$slug',
    path: '/learn/chapter/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/erros': typeof AuthenticatedErrosRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/hoeren': typeof AuthenticatedHoerenRoute
  '/lesen': typeof AuthenticatedLesenRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/schreiben': typeof AuthenticatedSchreibenRoute
  '/simulados': typeof AuthenticatedSimuladosRoute
  '/sprechen': typeof AuthenticatedSprechenRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/vocab': typeof AuthenticatedVocabRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/ingest': typeof AuthenticatedAdminIngestRoute
  '/learn/$level': typeof AuthenticatedLearnLevelRoute
  '/learn/chapter/$slug': typeof AuthenticatedLearnChapterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/erros': typeof AuthenticatedErrosRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/hoeren': typeof AuthenticatedHoerenRoute
  '/lesen': typeof AuthenticatedLesenRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/schreiben': typeof AuthenticatedSchreibenRoute
  '/simulados': typeof AuthenticatedSimuladosRoute
  '/sprechen': typeof AuthenticatedSprechenRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/vocab': typeof AuthenticatedVocabRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/ingest': typeof AuthenticatedAdminIngestRoute
  '/learn/$level': typeof AuthenticatedLearnLevelRoute
  '/learn/chapter/$slug': typeof AuthenticatedLearnChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/erros': typeof AuthenticatedErrosRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/hoeren': typeof AuthenticatedHoerenRoute
  '/_authenticated/lesen': typeof AuthenticatedLesenRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/schreiben': typeof AuthenticatedSchreibenRoute
  '/_authenticated/simulados': typeof AuthenticatedSimuladosRoute
  '/_authenticated/sprechen': typeof AuthenticatedSprechenRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/_authenticated/vocab': typeof AuthenticatedVocabRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/ingest': typeof AuthenticatedAdminIngestRoute
  '/_authenticated/learn/$level': typeof AuthenticatedLearnLevelRoute
  '/_authenticated/learn/chapter/$slug': typeof AuthenticatedLearnChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/erros'
    | '/flashcards'
    | '/hoeren'
    | '/lesen'
    | '/relatorios'
    | '/schreiben'
    | '/simulados'
    | '/sprechen'
    | '/tutor'
    | '/vocab'
    | '/api/chat'
    | '/auth/callback'
    | '/admin/ingest'
    | '/learn/$level'
    | '/learn/chapter/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/erros'
    | '/flashcards'
    | '/hoeren'
    | '/lesen'
    | '/relatorios'
    | '/schreiben'
    | '/simulados'
    | '/sprechen'
    | '/tutor'
    | '/vocab'
    | '/api/chat'
    | '/auth/callback'
    | '/admin/ingest'
    | '/learn/$level'
    | '/learn/chapter/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/erros'
    | '/_authenticated/flashcards'
    | '/_authenticated/hoeren'
    | '/_authenticated/lesen'
    | '/_authenticated/relatorios'
    | '/_authenticated/schreiben'
    | '/_authenticated/simulados'
    | '/_authenticated/sprechen'
    | '/_authenticated/tutor'
    | '/_authenticated/vocab'
    | '/api/chat'
    | '/auth/callback'
    | '/_authenticated/admin/ingest'
    | '/_authenticated/learn/$level'
    | '/_authenticated/learn/chapter/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vocab': {
      id: '/_authenticated/vocab'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof AuthenticatedVocabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sprechen': {
      id: '/_authenticated/sprechen'
      path: '/sprechen'
      fullPath: '/sprechen'
      preLoaderRoute: typeof AuthenticatedSprechenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simulados': {
      id: '/_authenticated/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof AuthenticatedSimuladosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schreiben': {
      id: '/_authenticated/schreiben'
      path: '/schreiben'
      fullPath: '/schreiben'
      preLoaderRoute: typeof AuthenticatedSchreibenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lesen': {
      id: '/_authenticated/lesen'
      path: '/lesen'
      fullPath: '/lesen'
      preLoaderRoute: typeof AuthenticatedLesenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hoeren': {
      id: '/_authenticated/hoeren'
      path: '/hoeren'
      fullPath: '/hoeren'
      preLoaderRoute: typeof AuthenticatedHoerenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/erros': {
      id: '/_authenticated/erros'
      path: '/erros'
      fullPath: '/erros'
      preLoaderRoute: typeof AuthenticatedErrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/$level': {
      id: '/_authenticated/learn/$level'
      path: '/learn/$level'
      fullPath: '/learn/$level'
      preLoaderRoute: typeof AuthenticatedLearnLevelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ingest': {
      id: '/_authenticated/admin/ingest'
      path: '/admin/ingest'
      fullPath: '/admin/ingest'
      preLoaderRoute: typeof AuthenticatedAdminIngestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/chapter/$slug': {
      id: '/_authenticated/learn/chapter/$slug'
      path: '/learn/chapter/$slug'
      fullPath: '/learn/chapter/$slug'
      preLoaderRoute: typeof AuthenticatedLearnChapterSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedErrosRoute: typeof AuthenticatedErrosRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedHoerenRoute: typeof AuthenticatedHoerenRoute
  AuthenticatedLesenRoute: typeof AuthenticatedLesenRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSchreibenRoute: typeof AuthenticatedSchreibenRoute
  AuthenticatedSimuladosRoute: typeof AuthenticatedSimuladosRoute
  AuthenticatedSprechenRoute: typeof AuthenticatedSprechenRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedVocabRoute: typeof AuthenticatedVocabRoute
  AuthenticatedAdminIngestRoute: typeof AuthenticatedAdminIngestRoute
  AuthenticatedLearnLevelRoute: typeof AuthenticatedLearnLevelRoute
  AuthenticatedLearnChapterSlugRoute: typeof AuthenticatedLearnChapterSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedErrosRoute: AuthenticatedErrosRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedHoerenRoute: AuthenticatedHoerenRoute,
  AuthenticatedLesenRoute: AuthenticatedLesenRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSchreibenRoute: AuthenticatedSchreibenRoute,
  AuthenticatedSimuladosRoute: AuthenticatedSimuladosRoute,
  AuthenticatedSprechenRoute: AuthenticatedSprechenRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedVocabRoute: AuthenticatedVocabRoute,
  AuthenticatedAdminIngestRoute: AuthenticatedAdminIngestRoute,
  AuthenticatedLearnLevelRoute: AuthenticatedLearnLevelRoute,
  AuthenticatedLearnChapterSlugRoute: AuthenticatedLearnChapterSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
